### PR TITLE
implement Clone/Copy for Offset

### PR DESCRIPTION
**Pull request by birkenfeld**

### CODE REVIEW

**Comment by birkenfeld** [comment]
Thanks! Can you release this?

**Comment by flosse** [comment]
done :)

**Comment by birkenfeld** [comment]
whoops, now ethercat 0.2.0 doesn't build anymore due to the new `AlState` overriding its own...

**Comment by flosse** [comment]
...oh no :(
I'm going to fix that.

**Comment by flosse** [comment]
ok, `v0.2.1` should work now.

**Comment by birkenfeld** [comment]
Nice, thanks!

**Comment by birkenfeld** [comment]
Just needs to be push the changes to the repo there :)

**Comment by flosse** [comment]
uups... sorry!

**Pull request merged**
